### ISSUE TITLE
Artifacts query gives incorrect artifact URLs sometimes

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4060]
Consider this job: https://hud.pytorch.org/pytorch/pytorch/pull/99617?sha=c5ca5ae4f6d030cb3c0085997a98fca1ce80bafa

According to the HUD (which is using rockset artifact query), the test-reports zip file for inductor_huggingface_dynamic https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/4764758120/1/artifact/test-reports-test-inductor_huggingface_dynamic-1-1-linux.g5.4xlarge.nvidia.gpu_12924959296.zip However, this zip file is empty.

We can also view the logs for this job: https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450

According to these logs, we upload a zip file with files in it:

```
Run # Remove any previous test reports if they exist
  # Remove any previous test reports if they exist
  rm -f test-reports-*.zip
  zip -r "test-reports-${FILE_SUFFIX}.zip" test -i '*.xml' -i '*.csv'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GIT_DEFAULT_BRANCH: main
    GPU_FLAG: --gpus all
    DOCKER_CONTAINER_ID: bde[25](https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450#step:17:27)96ed956e05e38723f7242837361fdad7e92e03bba378f4cab8bc6b28105
    FILE_SUFFIX: test-inductor_huggingface_dynamic-1-1-linux.g5.4xlarge.nvidia.gpu_129[26](https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450#step:17:28)190373
  adding: test/test-reports/inference_huggingface.csv (deflated 76%)
  adding: test/test-reports/training_huggingface.csv (deflated 75%)
```

However, notice that the actual zip file name we upload to is different(!!)

```
Run seemethere/upload-artifact-s3@v5
  with:
    s3-prefix: pytorch/pytorch/4765183591/1/artifact
  
    retention-days: 14
    if-no-files-found: error
    path: test-reports-*.zip
    name: artifact
    s3-bucket: gha-artifacts
    region: us-east-1
  env:
    GIT_DEFAULT_BRANCH: main
    GPU_FLAG: --gpus all
    DOCKER_CONTAINER_ID: bde2596ed956e05e38723f7242837361fdad7e92e03bba378f4cab8bc6b28105
NOTE: s3-prefix specified, ignoring name parameter
With the provided path, there will be 1 file uploaded
Uploading to s3 prefix: pytorch/pytorch/4[76](https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450#step:17:81)51[83](https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450#step:17:88)591/1/artifact
Starting upload of test-reports-test-inductor_huggingface_dynamic-1-1-linux.g5.4xlarge.nvidia.gpu_129261[90](https://github.com/pytorch/pytorch/actions/runs/4765183591/jobs/8471123450#step:17:96)373.zip
Finished upload of test-reports-test-inductor_huggingface_dynamic-1-1-linux.g5.4xlarge.nvidia.gpu_12926190373.zip
```

https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/4765183591/1/artifact/test-reports-test-inductor_huggingface_dynamic-1-1-linux.g5.4xlarge.nvidia.gpu_12926190373.zip is indeed non-empty and has the data I want.

It looks like rockset is returning a cancelled workflow for the commit in question: https://github.com/pytorch/pytorch/actions/runs/4764758120

Can we make it not do that? Latest workflow is probably always the correct one.
