### ISSUE TITLE
ARC dynamic rollout

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/test-infra#5132]
In the first comment should be a list of GitHub users who will use ARC runners.

**Comment by DanilBaibak** [comment]
```
experiments:
    lf:
        rollout_perc: 17
        all_branches: true
        workflows: ALL
    ephemeral:
        rollout_perc: 0
        all_branches: false
    wincanary:
        rollout_perc: 0
        all_branches: false
    wincanarylf:
        rollout_perc: 0
        all_branches: false
    arc:
        rollout_perc: 100
        all_branches: true
        default: false
        workflows: ALL
    amd-sandbox:
        rollout_perc: 100
        all_branches: true
        default: false
        workflows: trunk-rocm-sandbox
    amd-dpx:
        rollout_perc: 100
        all_branches: true
        default: false
        workflows: trunk, rocm-mi350, periodic-rocm-mi350, inductor-rocm-mi350, rocm-preview, slow
```
---
Opted-in:
 
#To opt out of an experiment, follow this example for the linux foundation runners (be sure to uncomment the line with your name):
#@yourGhUsername,-lf

@seemethere,arc
@zxiiro,lf
@jeanschmidt,-lf,arc
@wdvr,arc
@atalman,wincanarylf,lf
@huydhn,wincanarylf,-lf
@izaitsevfb,arc
@malfet,-lf
@georgehong,arc
@jathu,arc
#@yangw-dev,-arc
@amdfaa,amd-sandbox,amd-dpx
@akarale-nv,lf
