### ISSUE TITLE
Failure to Initialize Container: unsatisfied condition: cuda>=12.6

### ISSUE THREAD

**Issue by Jack-Khuu** [pytorch/test-infra#6465]
GPU based workflows fail after bumping Cuda requirements from 12.4 -> 12.6 in torchchat. 
Would love some help updating the driver or suggestions on how to update test config

Example Run: https://github.com/pytorch/torchchat/actions/runs/14053926197/job/39349546495
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: 
OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running prestart hook #0: exit status 1, stdout: , 

stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.6, 
please update your driver to a newer version, or use an earlier cuda container: unknown.
```
Test Runner Config: https://github.com/pytorch/torchchat/blob/fea361f6cce0b1cdd54cc211dde19266753b60fc/.github/workflows/more-tests.yml#L11-L19
```
  test-cuda:
    permissions:
      id-token: write
      contents: read
    uses: pytorch/test-infra/.github/workflows/linux_job_v2.yml@main
    with:
      runner: linux.g5.4xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: "12.6"
```

Similar related past Issue: https://github.com/pytorch/test-infra/issues/5191
